import { Ubuntu_Mono} from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Ubuntu_Mono({ subsets: ["latin"], weight:'400', });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        {children}
        </body>
    </html>
  );
}
